/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastructurestopwatch.GUI;

import datastruturestopwatch.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author donwhelan1
 */
public class Dash extends javax.swing.JPanel {

    /**
     * Creates new form Dash
     */
    private ArrayList<ArrayListDS> ALList;
    private ArrayDS array[];
    int ArrayIndex = 0;
    //int amountOfObjects = 100000;
    
    
    public Dash() {
        initComponents();
        ALList = new ArrayList<ArrayListDS>();
        //array = new ArrayDS [amountOfObjects];
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd10Elements = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSearchForLast = new javax.swing.JButton();
        txtAmountOfObjects = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        btnAdd10Elements.setText("Add Elements");
        btnAdd10Elements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd10ElementsActionPerformed(evt);
            }
        });

        Print.setText("print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jLabel1.setText("ArrayList");

        btnSearchForLast.setText("Search for last");
        btnSearchForLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchForLastActionPerformed(evt);
            }
        });

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd10Elements)
                                    .addComponent(btnSearchForLast)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(txtAmountOfObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 234, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Print, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAmountOfObjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd10Elements)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchForLast)
                .addGap(87, 87, 87)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Print))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd10ElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd10ElementsActionPerformed
        int idcounter, amountOfObjects;
        String stringAmountofObjects;
        idcounter = 1;
       long IteritiveStartNano = System.nanoTime();
       long IteritivestartMill = System.currentTimeMillis();
       
        stringAmountofObjects = txtAmountOfObjects.getText();
        amountOfObjects = Integer.parseInt(stringAmountofObjects);
        long IteritivetimeTakenNano = System.nanoTime() - IteritiveStartNano;
        long IteritivetimeTakenMill = System.currentTimeMillis() - IteritivestartMill;
        for(int i=0;i<=amountOfObjects-1;i++){
            ArrayListDS tempArrayList = new ArrayListDS();
            tempArrayList.setId(idcounter);
            ALList.add(tempArrayList);
            //array.append(idcounter);
            idcounter ++;
        }
        JOptionPane.showMessageDialog(null,"Added objects" + "\ntime taken in nano seconds: " + IteritivetimeTakenNano + "\ntime taken in milli seconds: " + IteritivetimeTakenMill);
        
    }//GEN-LAST:event_btnAdd10ElementsActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        
        for(int i=0;i<ALList.size(); i++){
            ArrayListDS tempArrayListDS = ALList.get(i);
            String tempInfo = tempArrayListDS.toString();
            JOptionPane.showMessageDialog(null,tempInfo);
        }
        
    }//GEN-LAST:event_PrintActionPerformed

    private void btnSearchForLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchForLastActionPerformed

       int idToFind;
       idToFind = ALList.size();
       long IteritiveStartNano = System.nanoTime();
       long IteritivestartMill = System.currentTimeMillis();
       
       for(int i=0;i<ALList.size();i++){
           ArrayListDS tempArrayListDS = ALList.get(i);
           int tempId = tempArrayListDS.getId();
           if(idToFind==(tempId)){
               String tempInfo = tempArrayListDS.toString();
               long IteritivetimeTakenNano = System.nanoTime() - IteritiveStartNano;
               long IteritivetimeTakenMill = System.currentTimeMillis() - IteritivestartMill;
               JOptionPane.showMessageDialog(null,"Found " + tempInfo + "\n\nIteritive - \n" + "time taken in nano seconds: " + IteritivetimeTakenNano + "\ntime taken in milli seconds: " + IteritivetimeTakenMill);   
           }
       }
       
       long RecursiveStartNano = System.nanoTime();
       long RecursivestartMill = System.currentTimeMillis();
       //recursuceSearch(amountOfObjects);
       long RecursivetimeTakenNano = System.nanoTime() - RecursiveStartNano;
       long RecursivetimeTakenMill = System.currentTimeMillis() - RecursivestartMill;
       
       txtAmountOfObjects.setText("");
    }//GEN-LAST:event_btnSearchForLastActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ALList.clear();
       JOptionPane.showMessageDialog(null, "cleared");
    }//GEN-LAST:event_jButton1ActionPerformed

//public void recursuceSearch(int n) {
//           if( n == amountOfObjects ){
//               JOptionPane.showMessageDialog(null,"Found" + tempInfo + "Recursive - \n" + "time taken in nano seconds: " + RecursivetimeTakenNano + "\ntime taken in milli seconds: " + IteritivetimeTakenMill);
//           }
//           else{
//               solve(n-1,start,end,third);
//               System.out.println(start + " --> " + end);
//               solve(n-1,third,start,end);
//           }
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JButton btnAdd10Elements;
    private javax.swing.JButton btnSearchForLast;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmountOfObjects;
    // End of variables declaration//GEN-END:variables
}
